spring:
  main:
    show-banner : false
  thymeleaf:
    cache : false
    server:
    port: 8443
    ssl:
    key-store: file:///path/to/mykeys.jks
    key-store-password: letmein
    key-password: letmein
